# Generated by Django 3.2.8 on 2021-10-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
