# Generated by Django 3.2.8 on 2021-10-15 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Remisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=50)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.atencionmedica')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripción', models.TextField(max_length=500)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.atencionmedica')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('hora', models.DateField(auto_now_add=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.atencionmedica')),
            ],
        ),
    ]
