# Generated by Django 3.2.8 on 2021-10-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionmedica',
            name='estado',
            field=models.CharField(choices=[('activa', 'activa'), ('finalizada', 'finalizada')], default='activa', max_length=80),
        ),
        migrations.AddField(
            model_name='atencionmedica',
            name='medico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
